apiVersion: apps/v1
kind: Deployment
metadata:
  name: lg-oled-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lg-oled
  template:
    metadata:
      labels:
        app: lg-oled
    spec:
      containers:
        - name: lg-oled
          image: registry.digitalocean.com/fabs/lg-oled:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: fabs      
          